### ISSUE TITLE
Install the app Linux Mint 21.x (or Windows)

### ISSUE THREAD

**Issue by pa2eon** [F4JTV/CPyS-891#1]
Dear OM,

Found your nice python prog.
I will se if I can use this .. but at wha OS platform you prefer, Linux or Windows.
And what will be he best .. can I use Thonny also to handle the python app ?

Regards,
Eric, PA2EON

**Comment by pa2eon** [comment]
I have the software up and running on Linux Mint 21.x
With the next prepared functions:

- sudo apt-get install python3-pip
- pip install pyserial
- pip install PyQT5
And then started the fresh program: 
- python3 ./CPyS_891.py

**Comment by F4JTV** [comment]
Dear Eric,
Thank you for enjoying my little app, it is not finished yet, but i work actively on it.
It is a crossplatform script who work on Windows, Linux and i think MacOs. It use CAT control to access all parameters of the FT-891.
For now, i don't have inplemented the choice for the path of the COM port and baudrate, i will do it this weekend.
I will write a little manual to explain how to use it. You just have Python3 installed on your computer.
Best regards,
Yoann COLLIN
F4JTV
73
----------------De : PA2EON ***@***.***>Envoyé : vendredi 26 mai 2023 10:30À : F4JTV/CPyS-891 ***@***.***>Cc : Subscribed ***@***.***>Objet : [F4JTV/CPyS-891] At what platform is the app for ( Linux or Windows) (Issue #1)
Dear OM,
Found your nice python prog.
I will se if I can use this .. but at wha OS platform you prefer, Linux or Windows.
And what will be he best .. can I use Thonny also to handle the python app ?
Regards,
Eric, PA2EON

**Comment by F4JTV** [comment]
> Hi Yoann, Many thanks for your reply. I 'am busy on the moment to install different software parts for the FT-891. On the internet their is no free-ware software to find to handle the memory and setup settings in the Rig. At my github you will find a 'new'  version of QSSTV in QT6 programmed. Next week and after it .. I will make new code for more digital signals for SSTV.  Your program I will need .. because it wil give an very easy setup of all the parms in the RIG. After 3 weeks I' am going to norway and the rig is with me .. for winlink, sstv and FT8 dig .. so maybe we can make an contact, also at 20 or 40 meter SSB. Keep in contact, Met vriendelijke groeten, Kind regards, Eric Oosterbaan / PA2EON T: +31 73 5530052 E: ***@***.*** H: http://www.pa2eon.nl W: http://www.amsat-nl.org
> […](#)
> ----- Originele bericht ----- Van: F4JTV ***@***.***) Datum: 26-05-2023 15:13 Naar: F4JTV/CPyS-891 ***@***.***) Cc: PA2EON ***@***.***), Author ***@***.***) Onderwerp: Re: [F4JTV/CPyS-891] Install the app Linux Mint 21.x (or Windows) (Issue #1) Dear Eric, Thank you for enjoying my little app, it is not finished yet, but i work actively on it. It is a crossplatform script who work on Windows, Linux and i think MacOs. It use CAT control to access all parameters of the FT-891. For now, i don't have inplemented the choice for the path of the COM port and baudrate, i will do it this weekend. I will write a little manual to explain how to use it. You just have Python3 installed on your computer. Best regards, Yoann COLLIN F4JTV 73 ----------------De : PA2EON ***@***.***>Envoyé : vendredi 26 mai 2023 10:30À : F4JTV/CPyS-891 ***@***.***>Cc : Subscribed ***@***.***>Objet : [F4JTV/CPyS-891] At what platform is the app for ( Linux or Windows) (Issue #1) Dear OM, Found your nice python prog. I will se if I can use this .. but at wha OS platform you prefer, Linux or Windows. And what will be he best .. can I use Thonny also to handle the python app ? Regards, Eric, PA2EON —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

There is no free software for setup quickly the FT-891, event CHIRP, and that is why i do this script. Fortunately, Yaesu provide a complete documentation for the FT-891 CAT control. That going to take some time to implement all the features (functions and memory, saving and open a config file) but It's worth it, there are a lot of user of this transceiver.

**Comment by F4JTV** [comment]
Instruction for the installation is in the readme.md
